### ISSUE TITLE
Karma tests failure

### ISSUE THREAD

**Issue by ufoscout** [vsavkin/state_management_ngrx4#2]
All tests fail when executing `npm run test`:

```
22 08 2017 12:21:00.847:INFO [Chrome 60.0.3112 (Linux 0.0.0)]: Connected on socket wNdGVSze3gUsiMvnAAAC with id 86580283
Chrome 60.0.3112 (Linux 0.0.0) AppComponent should create the app FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34522:42)
Chrome 60.0.3112 (Linux 0.0.0): Executed 1 of 3 (1 FAILED) (0 secs / 0.044 secs)
Chrome 60.0.3112 (Linux 0.0.0) AppComponent should create the app FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.Chrome 60.0.3112 (Linux 0.0.0) AppComponent should have as title 'app' FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34522:42)
Chrome 60.0.3112 (Linux 0.0.0): Executed 2 of 3 (2 FAILED) (0 secs / 0.079 secs)
Chrome 60.0.3112 (Linux 0.0.0) AppComponent should have as title 'app' FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.Chrome 60.0.3112 (Linux 0.0.0) AppComponent should render title in a h1 tag FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34522:42)
Chrome 60.0.3112 (Linux 0.0.0): Executed 3 of 3 (3 FAILED) (0 secs / 0.095 secs)
Chrome 60.0.3112 (Linux 0.0.0) AppComponent should render title in a h1 tag FAILED
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34530:37)
        'router-outlet' is not a known element:
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9507:34)
            at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:9876/_karma_webpack_/vendor.bundle.js:20627:19)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34779:39)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:62
            at Set.forEach (native)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34699:19)
            at http://localhost:9876/_karma_webpack_/vendor.bundle.js:34600:19
            at Object.then (http://localhost:9876/_karma_webpack_/vendor.bundle.js:9496:148)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.bundle.js:34598:26)
            at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.Chrome 60.0.3112 (Linux 0.0.0): Executed 3 of 3 (3 FAILED) ERROR (0.125 secs / 0.095 secs)

```

**Comment by kukiel** [comment]
@ufoscout There is only one spec file for initial app component tests so it is obviously failing as it's unmodified. However it would be great to also include tests for educational purposes @vsavkin. Anyway, great job!
